/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicolombo.pb.proaula.views;

import javax.swing.JOptionPane;

/**
 *
 * @author yulin
 */
public class ventanaCuenta extends javax.swing.JFrame {

    /**
     * Creates new form ventanaCuenta
     */
    public ventanaCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        cuentaeti = new javax.swing.JLabel();
        etiProductos = new javax.swing.JLabel();
        etiCantidad = new javax.swing.JLabel();
        etiPrecio = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        etiTotal = new javax.swing.JLabel();
        botonFinalizar = new javax.swing.JButton();
        eticuenta = new javax.swing.JLabel();

        jLabel25.setText("$");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuenta");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cuentaeti.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cuentaeti.setText("Cuenta");
        getContentPane().add(cuentaeti, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 100, 40));

        etiProductos.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiProductos.setText("Productos");
        getContentPane().add(etiProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, -1));

        etiCantidad.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiCantidad.setText("Cantidad");
        getContentPane().add(etiCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        etiPrecio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiPrecio.setText("precio");
        getContentPane().add(etiPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 410, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 353, 410, 10));

        etiTotal.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiTotal.setText("Total");
        getContentPane().add(etiTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 60, 20));

        botonFinalizar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botonFinalizar.setText("Finalizar");
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(botonFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        eticuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_cuenta.jpg"))); // NOI18N
        getContentPane().add(eticuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
JOptionPane.showMessageDialog(null,"Gracias por preferir Bambino que tenga un feliz dia.");

    }//GEN-LAST:event_botonFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFinalizar;
    private javax.swing.JLabel cuentaeti;
    private javax.swing.JLabel etiCantidad;
    private javax.swing.JLabel etiPrecio;
    private javax.swing.JLabel etiProductos;
    private javax.swing.JLabel etiTotal;
    private javax.swing.JLabel eticuenta;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
