/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicolombo.pb.proaula.views;

import co.edu.unicolombo.pb.proaula.conceptos.Cliente;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
<<<<<<< HEAD
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.Icon;
=======
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
>>>>>>> f85604225e10e98b11d10938d9c3cbe838c4932e
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    String[] documento;

public VentanaPrincipal() {
        initComponents();
<<<<<<< HEAD
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screenSize.getWidth() - this.getWidth()) / 2);
    int y = (int) ((screenSize.getHeight() - this.getHeight()) / 2);

    this.setLocation(x, y);
        btnSiguiente.setEnabled(false);
        
=======
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

    // Calcular la ubicación para centrar la ventana
    int x = (int) ((screenSize.getWidth() - this.getWidth()) / 2);
    int y = (int) ((screenSize.getHeight() - this.getHeight()) / 2);

    // Establecer la ubicación de la ventana para que aparezca centrada
    this.setLocation(x, y);
        btnSiguiente.setEnabled(false);
>>>>>>> f85604225e10e98b11d10938d9c3cbe838c4932e
        SetImageLabel(etiImagen, "src/imagenes/comida italiana.jpg");
        
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bienvenida = new javax.swing.JLabel();
        etiNombre = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        documentoText = new javax.swing.JTextField();
        etiDocumento = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        etiMensaje2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textMensaje = new javax.swing.JTextArea();
        etiImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bambino");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenida.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 28)); // NOI18N
        bienvenida.setForeground(new java.awt.Color(255, 255, 255));
        bienvenida.setText("Registro del cliente");
        bienvenida.setAlignmentX(0.5F);
<<<<<<< HEAD
        getContentPane().add(bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));
=======
        getContentPane().add(bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));
>>>>>>> f85604225e10e98b11d10938d9c3cbe838c4932e

        etiNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiNombre.setForeground(new java.awt.Color(255, 255, 255));
        etiNombre.setText("Nombre completo:");
<<<<<<< HEAD
        getContentPane().add(etiNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 107, 24));

        nombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextActionPerformed(evt);
            }
        });
        getContentPane().add(nombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 218, 31));

        documentoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoTextActionPerformed(evt);
            }
        });
        getContentPane().add(documentoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 218, 31));
=======
        getContentPane().add(etiNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 160, 24));
>>>>>>> f85604225e10e98b11d10938d9c3cbe838c4932e

        nombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextActionPerformed(evt);
            }
        });
        getContentPane().add(nombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 218, 31));

        documentoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoTextActionPerformed(evt);
            }
        });
        getContentPane().add(documentoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 218, 31));

        etiDocumento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiDocumento.setForeground(new java.awt.Color(255, 255, 255));
        etiDocumento.setText("Número documento:");
<<<<<<< HEAD
        getContentPane().add(etiDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 126, 24));
=======
        getContentPane().add(etiDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 180, 24));
>>>>>>> f85604225e10e98b11d10938d9c3cbe838c4932e

        btnSiguiente.setBackground(new java.awt.Color(153, 255, 153));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));
=======
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));
>>>>>>> f85604225e10e98b11d10938d9c3cbe838c4932e

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        etiMensaje2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiMensaje2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(etiMensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 198, 25));
=======
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        etiMensaje2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiMensaje2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(etiMensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 198, 25));
>>>>>>> f85604225e10e98b11d10938d9c3cbe838c4932e

        textMensaje.setEditable(false);
        textMensaje.setColumns(20);
        textMensaje.setRows(5);
        textMensaje.setBorder(null);
        jScrollPane1.setViewportView(textMensaje);

<<<<<<< HEAD
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 326, 92));
        getContentPane().add(etiImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 560));
=======
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 326, 92));

        etiImagen.setPreferredSize(new java.awt.Dimension(550, 400));
        getContentPane().add(etiImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 560));
>>>>>>> f85604225e10e98b11d10938d9c3cbe838c4932e

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Cliente.nombre = nombreText.getText();
        Cliente.documento = documentoText.getText();
        if(Cliente.nombre.isEmpty() || !validarCaracteres(Cliente.nombre) || Cliente.nombre.charAt(0)==' '){
            JOptionPane.showMessageDialog(null,"Nombre invalido.");
            return;
        }
        
        if(!validarNumeros(Cliente.documento) || Cliente.documento.isEmpty()){
            JOptionPane.showMessageDialog(null, "Número de documento invalido.");
            return;
        }
        
        textMensaje.setText("Sr(a) "+Cliente.nombre+"\nEstamos muy felices de atenderlo(a) el día de hoy.\n" +"\nNumero de identificación del cliente: "+Cliente.documento);
        etiMensaje2.setText("Registro realizado con exito");
<<<<<<< HEAD
        btnSiguiente.setEnabled(true);
=======
        
        btnSiguiente.setEnabled(true);
        
>>>>>>> f85604225e10e98b11d10938d9c3cbe838c4932e
        try {
        BufferedWriter writer = new BufferedWriter(new FileWriter("Datos.txt", true));
        writer.write("DATOS CLIENTE");
        writer.newLine();
        writer.write("\nNombre: " + Cliente.nombre +"\nDocumento: "+Cliente.documento+"\n");
        writer.write("");
        writer.newLine();

        writer.close();
    } catch (IOException e) {
        System.err.println("Error al escribir en el archivo.");
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
    MenuRestaurante menu = new MenuRestaurante();
    
            this.setVisible(false);
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void nombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextActionPerformed
<<<<<<< HEAD
     documentoText.requestFocus();
    }//GEN-LAST:event_nombreTextActionPerformed

    private void documentoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoTextActionPerformed
    btnGuardar.doClick();
=======
        // TODO add your handling code here:
                documentoText.requestFocus();
    }//GEN-LAST:event_nombreTextActionPerformed

    private void documentoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoTextActionPerformed
        // TODO add your handling code here:
                btnGuardar.doClick();
>>>>>>> f85604225e10e98b11d10938d9c3cbe838c4932e
    }//GEN-LAST:event_documentoTextActionPerformed
    
    public void SetImageLabel(JLabel nombrelabel, String root){
        
    this.addComponentListener(new ComponentAdapter() {
    @Override
    public void componentResized(ComponentEvent e) {
       
        ImageIcon icono = new ImageIcon(root);
        Image imagen = icono.getImage().getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH);
        
        
        nombrelabel.setBounds(0,0,getWidth(), getHeight());
        nombrelabel.setIcon(new ImageIcon(imagen));
    }
});

    }
    public static boolean validarCaracteres(String datos){
        return datos.matches("[a-z A-Z]*");
    }
    public static boolean validarNumeros(String datos){
        return datos.matches("[0-9]*");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenida;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JTextField documentoText;
    private javax.swing.JLabel etiDocumento;
    private javax.swing.JLabel etiImagen;
    private javax.swing.JLabel etiMensaje2;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreText;
    private javax.swing.JTextArea textMensaje;
    // End of variables declaration//GEN-END:variables
}
