/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author alvar
 */
public final class MenuRestaurante extends javax.swing.JFrame {

    /**
     * Creates new form MenuRestaurante
     */
    public MenuRestaurante() {
        initComponents();
         SetImageLabel(etiPizza,"src/imagenes/pizza.jpeg");
         SetImageLabel(PastasBolognesa,"src/imagenes/pastas.jpeg");
         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        etiPizza = new javax.swing.JLabel();
        PizzaNapolitana = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        PastasBolognesa = new javax.swing.JLabel();
        AguaCristal = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        etiAgua = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 45, -1));
        getContentPane().add(etiPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 200, 120));

        PizzaNapolitana.setForeground(new java.awt.Color(255, 255, 255));
        PizzaNapolitana.setText("Pizza napolitana");
        getContentPane().add(PizzaNapolitana, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 90, 20));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 630, 50, -1));

        PastasBolognesa.setForeground(new java.awt.Color(255, 255, 255));
        PastasBolognesa.setText("Pastas Bolognesas");
        getContentPane().add(PastasBolognesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 90, -1));

        AguaCristal.setForeground(new java.awt.Color(255, 255, 255));
        AguaCristal.setText("Agua Cristal");
        getContentPane().add(AguaCristal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 100, 20));
        getContentPane().add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 50, -1));

        etiAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agua.jpeg"))); // NOI18N
        getContentPane().add(etiAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 146, 210, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void SetImageLabel(JLabel nombrelabel, String root){
        ImageIcon imagen = new ImageIcon(root); 
        Icon icon = new ImageIcon(
                imagen.getImage().getScaledInstance(nombrelabel.getWidth(), nombrelabel.getHeight(), Image.SCALE_DEFAULT));
        nombrelabel.setIcon(icon);
        this.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AguaCristal;
    private javax.swing.JLabel PastasBolognesa;
    private javax.swing.JLabel PizzaNapolitana;
    private javax.swing.JLabel etiAgua;
    private javax.swing.JLabel etiPizza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    // End of variables declaration//GEN-END:variables

    
}
